# Sample configuration for freshrss-filter

[openai]
# Your OpenAI API key
api_key = "sk-..."
# Optional: API base and model
# api_base = "https://api.openai.com/v1"
# model = "gpt-4o-mini"
# temperature = 0.0
# max_tokens = 256
# Confidence threshold for ad decision (0.0-1.0)
threshold = 0.6
# System prompt used by the classifier
system_prompt = """
你是一个专业的信息价值鉴别器，拥有跨领域的专业知识和洞察力。
你的任务是从一个科技爱好者(Tech Nerd)的角度评估RSS信息的价值。

请分析以下方面：
1) 该信息在相关领域的重要性
2) 对普通人实际生活的潜在影响
3) 信息的原创性和突破性
4) 是否只是营销炒作或无意义的更新

请以专业但客观的标准来判断，避免被媒体夸大其词的标题误导。

回复JSON格式：{\"is_ad\": boolean, \"confidence\": 0..1, \"reason\": string}
"""

[freshrss]
# FreshRSS base URL (with or without trailing slash)
base_url = "https://freshrss.example.com"
# Fever API key (FreshRSS -> User -> API management)
fever_api_key = "<fever_api_key>"
# User-Agent string for requests
user_agent = "freshrss-filter/0.1"

# Action when an item is classified as ad:
# - "mark_read" (default): mark as read using Fever API
# - "label": add GReader label (spam_label) and mark as read
delete_mode = "label"

# Only required when delete_mode = "label"
greader_username = "your_username"
greader_password = "your_password"
spam_label = "Ads"

[scheduler]
# Cron schedule with seconds field (e.g., every 10 minutes)
cron = "0 */10 * * * *"

[database]
# SQLite database file path
path = "freshrss-filter.db"

# Top-level override to prevent write actions
dry_run = false

